MyRssServer/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using MyRssServer.Areas.HelpPage.ModelDescriptions;
using MyRssServer.Areas.HelpPage.Models;

namespace MyRssServer.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

MyRssServer/Views/Shared/ItemDetails.cshtml
@{
    Layout = null;
}
<div>
    <div class="col-lg-12">
        <h2>
            {{item.title}}
        </h2>
    </div>
    <div class="col-lg-12">
        <img src="http://dummyimage.com/640x480/000/fff" />
    </div>
    <div class="col-lg-12">
        <div class="item-view-description">
            <p>{{item.description}}</p>
        </div>
    </div>
    <a ng-href="{{item.link}}">Visit website</a>
</div>

MyRssServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/font-awesome.css")
    @Styles.Render("~/Content/Site.css")*@
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body ng-app="RSSApp">
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </div>
            </div>
        </div>*@
    <div class="container-fluid main-container" ng-controller="mainCtrl">
        <div class="row">
            @RenderBody()
        </div>
        @*<hr />*@
        @*<footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/Scripts/angular.js")
    @Scripts.Render("~/Scripts/bower")
    @*@Scripts.Render("~/Scripts/angular-ui.js")*@
    @RenderSection("scripts", required: false)
    @*<script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.2/ui-bootstrap-tpls.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.2/ui-bootstrap.js" type="text/javascript"></script>*@
    <script src="http://pvdspek.github.io/downloads/jquery.autoellipsis-1.0.10.js" type="text/javascript"></script>
</body>
</html>